### PR TITLE
Fix nullwarnings in OSGi event handling

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
I don't understand that changes.
Why do you want to allow a nullable value for the key?
I don't think we need to add a null value to a key at any place.
Where is null be used?

Warnings that has been caused by missing EEAs should not be solved by adding an explicit nullable. IIRC this has not been done until now.

**Comment by triller-telekom** [comment]
I am not adding `@Nullable` to the key, but to the **value**. I.e. I am allowing that this can happen:

```
typedEventFactories.put("myFactory", null);
```

You have the `null` check where you `get()` an `EventFactory` from that map.

Or, as I know think about it again: Do you mean that you never want to have a `null` factory in that map and also ensure that in your code, but then the `Map.get("invalidKey")` method will return `null` becasue that key is not in the map? If **that** is what you wanted, I agree with you that we do need external annotations to cover that.

**Comment by maggu2810** [comment]
> I am not adding `@Nullable` to the key, but to the **value**.

I know and that was what I comment.

> Why do you want to allow a nullable value for the key?

The words "key" and also the word "value" refers to the key-value pair of the map.
So "a nullable value for the key" means (or at least it has been my intention) "a key that value if null in the map".
Don't interpret "value for the key", "the key itself" but the value of the map referenced by that key.

I hope my meaning has been clear now. :wink:

And yes `Map.get("invalidKey")` will ever return null regardless if a nullable, non-null or not annotated value is used.

**Comment by triller-telekom** [comment]
Thanks for the clarification of my misunderstanding. I am closing this PR now.

**Pull request closed without merging**
